"""retactor bd

Revision ID: 1dfa7fa91476
Revises: 
Create Date: 2021-01-19 18:12:00.925386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfa7fa91476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produtores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('link_foto', sa.String(), nullable=True),
    sa.Column('link_video', sa.String(), nullable=True),
    sa.Column('fk_produtor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_produtor'], ['produtores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_produtores_consumidores',
    sa.Column('fk_produtor', sa.Integer(), nullable=True),
    sa.Column('fk_consumidor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_consumidor'], ['consumidores.id'], ),
    sa.ForeignKeyConstraint(['fk_produtor'], ['produtores.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_produtores_consumidores')
    op.drop_table('produtos')
    op.drop_table('produtores')
    op.drop_table('consumidores')
    # ### end Alembic commands ###
