"""criaçao das tabelas

Revision ID: a33086ccfa92
Revises: 
Create Date: 2021-01-12 21:15:05.742161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33086ccfa92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtores_consumidores',
    sa.Column('produtores_id', sa.Integer(), nullable=True),
    sa.Column('consumidores_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumidores_id'], ['consumidores.id'], ),
    sa.ForeignKeyConstraint(['produtores_id'], ['produtores.id'], )
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('link_foto', sa.String(), nullable=True),
    sa.Column('link_video', sa.String(), nullable=True),
    sa.Column('fk_produtores', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_produtores'], ['produtores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    op.drop_table('produtores_consumidores')
    op.drop_table('produtores')
    op.drop_table('consumidores')
    # ### end Alembic commands ###
